/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

`DEFINE_CUSTOM_INSTR(THEAD_ADDSL, R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_SRRI,  R_FORMAT, SHIFT,      RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_SRRIW, R_FORMAT, SHIFT,      RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_TSTNBZ, R_FORMAT, LOGICAL,   RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_REV,   R_FORMAT, LOGICAL,    RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_FF0,   R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_FF1,   R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_TST,   R_FORMAT, LOGICAL,    RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_REVW,  R_FORMAT, LOGICAL,    RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_EXT,   R_FORMAT, LOGICAL,    RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_EXTU,  R_FORMAT, LOGICAL,    RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MVEQZ, R_FORMAT, LOGICAL,    RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MVNEZ, R_FORMAT, LOGICAL,    RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MULA,  R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MULS,  R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MULAW, R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MULSW, R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MULAH, R_FORMAT, ARITHMETIC, RV64X)
`DEFINE_CUSTOM_INSTR(THEAD_MULSH, R_FORMAT, ARITHMETIC, RV64X)
